name: Code Checkout Only

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  just-checkout:
    runs-on: ubuntu-latest

    steps:
      - name: 🔄 Checkout Code
        uses: actions/checkout@v3

      - name: 🧪 Echo test
        run: echo "Workflow triggered and code checked out successfully!"