name: Node.js App CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 🧾 Checkout source code
        uses: actions/checkout@v3

      - name: 🧰 Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Apne app ka Node version yahan daal

      - name: 📦 Install dependencies
        run: npm install

      - name: 🚀 Run App (for testing purpose)
        run: node server.js

      # ✅ OPTIONAL: Render Deployment Step
      - name: 📡 Deploy to Render
        run: curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK }}
