name: Node.js App CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' # tu jo version use karta hai woh daal

      - name: Install dependencies
        run: npm install

      - name: Run App (optional - sirf check ke liye)
        run: node server.js

      - name: Run Linter (optional)
        run: |
          echo "No linter configured yet"

      - name: Run Tests (optional)
        run: |
          echo "No tests configured yet"
